version: '3.8'

services:
  localstack:
    container_name: idp_localstack
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # External service port range
    environment:
      - SERVICES=s3,dynamodb,kms,lambda,sqs
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./.localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
