apiVersion: v1
kind: Secret
metadata:
  name: backupper-env
type: Opaque
stringData:
  DATABASE_URL: postgres://backupper:backupper@postgres:5432/backupper?sslmode=disable
  AWS_ENDPOINT_URL: http://localstack:4566
  AWS_ACCESS_KEY_ID: test
  AWS_SECRET_ACCESS_KEY: test
  AWS_REGION: us-east-1
  S3_BUCKET: db-backups
  S3_PREFIX: daily
  APP_ENV: dev
  ZSTD_LEVEL: "3"
  MAX_SCHEDULE_FAILURES: "5"
