apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: idp-db-backupper

resources:
  - namespace.yaml
  - postgres.yaml
  - localstack.yaml

commonLabels:
  app.kubernetes.io/part-of: idp-db-backupper
