apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: idp-db-toolchain

resources:
  - namespace.yaml
  - postgres-secret.yaml
  - postgres-init.yaml
  - postgres.yaml
  - localstack.yaml
  - db-toolchain-config.yaml
  - db-toolchain-deployment.yaml
  - db-toolchain-service.yaml
  - prometheus-config.yaml
  - prometheus-rules.yaml
  - prometheus.yaml
  - grafana-provisioning.yaml
  - grafana.yaml

commonLabels:
  app.kubernetes.io/part-of: idp-db-toolchain

secretGenerator:
  - name: db-toolchain-env
    literals:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    options:
      disableNameSuffixHash: true
