apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: idp-db-backupper

resources:
  - ../namespace.yaml
  - serviceaccount.yaml
  - backupper-config.yaml
  - backupper-deployment.yaml
  - ../backupper-service.yaml
  - ../prometheus-rules.yaml

commonLabels:
  app.kubernetes.io/part-of: idp-db-backupper
  app.kubernetes.io/managed-by: idp-db-backupper

images:
  - name: idp-db-backupper
    newName: ghcr.io/your-org/idp-db-backupper
    newTag: latest
